#!/usr/bin/env bash
# Generated by pivota-spec init-dev-server
# Catalog entry: react-next
# Generator version: init-dev-server@1
#
# Edits ABOVE the END PIVOTA PREAMBLE marker are reset on regen.
# Edits BELOW the marker are preserved on regen.
#
# Why these choices (decision-trace; do not delete):
#   - `set -euo pipefail` not just `-e` — RESEARCH.md Pitfall 4 (silent pipe failures).
#   - `sha256sum` for lockfile hashing — RESEARCH.md "Don't hand-roll" (universal
#     coreutils, no extra dep vs blake3 / git hash-object / md5sum).
#   - Backoff 1s / 2s / 4s — Claude's Discretion per CONTEXT.md (small base, predictable).
#   - Log destination `/tmp/pivota-dev.log` — Open Question #4 resolved (always
#     writable inside Daytona sandboxes; matches existing convention).
#   - Lockfile-sentinel skip combined with INSTALL_PRESENCE_CHECK — RESEARCH.md
#     Pitfall 6 (sentinel survives reboots but install output dirs may not on
#     fresh tmpfs; never skip on a clean directory).
#   - Retry exits with INNER command's last exit code (not a fixed 1) so callers
#     can disambiguate failures from the wrapper.

set -euo pipefail

# === Bash version guard (RESEARCH.md Pitfall 8) ===
# `wait -n` (used by the multi-process variant) requires bash >= 4.3.
# Fail fast with a clear message; do not silently degrade.
if (( BASH_VERSINFO[0] < 4 )) || { (( BASH_VERSINFO[0] == 4 )) && (( BASH_VERSINFO[1] < 3 )); }; then
  echo "[pivota] bash 4.3+ required for 'wait -n'; found ${BASH_VERSION}" >&2
  exit 127
fi

# === D-11.4: tee stdout/stderr to /tmp/pivota-dev.log AND pass through ===
mkdir -p /tmp
exec > >(tee -a /tmp/pivota-dev.log) 2>&1
echo "[pivota] $(date -Iseconds) start-dev.sh begin (catalog: react-next)"

# === D-11.1 + D-11.2: per-stack 0.0.0.0 binding + host allowlist relaxation ===
# HOSTNAME is honored by Next.js for the dev server bind address since v13.
export HOSTNAME=0.0.0.0
export HOST=0.0.0.0

# === D-11.3: .env.example -> .env transitional copy (until Phase 38) ===
if [[ ! -f .env && -f .env.example ]]; then
  echo "[pivota] copying .env.example -> .env (Phase 38 will replace this hack)"
  cp .env.example .env
fi

# === Pre-exec snippet: allowedDevOrigins overlay for sandbox preview iframe ===
for CFG in next.config.mjs next.config.js next.config.ts; do
  if [[ -f "$CFG" ]]; then
    if ! grep -q "allowedDevOrigins" "$CFG" 2>/dev/null; then
      mkdir -p .pivota
      cat > .pivota/next.config.pivota.cjs <<'EOF'
// Auto-generated by pivota init-dev-server. Extends user's next.config to permit
// Daytona preview origin embedding in dev. Phase 39 will refine this; for now
// the overlay is a best-effort seed that only takes effect for Next versions
// that expose a dynamic config-merge hook (see Notes in catalog entry).
module.exports = (phase, { defaultConfig }) => {
  let user = {};
  try { user = require('../next.config.js'); }
  catch { try { user = require('../next.config.mjs').default || {}; } catch {} }
  if (typeof user === 'function') user = user(phase, { defaultConfig });
  return {
    ...user,
    allowedDevOrigins: [
      ...(user.allowedDevOrigins || []),
      '*.preview.daytona.io',
      '*.daytona.work',
    ],
  };
};
EOF
      echo "[pivota] wrote .pivota/next.config.pivota.cjs (allowedDevOrigins overlay)"
    fi
    break
  fi
done

# === D-12: idempotent install via lockfile hash + presence check ===
SENTINEL="/tmp/pivota-setup-sentinel"
LOCK_FILE_PATH="package-lock.json"
INSTALL_PRESENCE_CHECK="node_modules"
INSTALL_CMD='npm ci || npm install'

run_install() {
  echo "[pivota] running install: $INSTALL_CMD"
  bash -c "$INSTALL_CMD"
}

if [[ -n "$LOCK_FILE_PATH" && -f "$LOCK_FILE_PATH" ]]; then
  CURRENT_HASH=$(sha256sum "$LOCK_FILE_PATH" | cut -d' ' -f1)
  PREVIOUS_HASH=$(cat "$SENTINEL" 2>/dev/null || echo "")

  PRESENCE_OK=1
  if [[ -n "$INSTALL_PRESENCE_CHECK" && ! -e "$INSTALL_PRESENCE_CHECK" ]]; then
    PRESENCE_OK=0
  fi

  if [[ "$CURRENT_HASH" == "$PREVIOUS_HASH" && "$PRESENCE_OK" == "1" ]]; then
    echo "[pivota] lockfile unchanged AND install output present; skipping install"
  else
    if [[ "$PRESENCE_OK" == "0" ]]; then
      echo "[pivota] install output ($INSTALL_PRESENCE_CHECK) missing; install required"
    else
      echo "[pivota] lockfile changed (or first boot); install required"
    fi
    run_install
    echo "$CURRENT_HASH" > "$SENTINEL"
  fi
elif [[ -n "$INSTALL_CMD" ]]; then
  if [[ ! -f "$SENTINEL" ]]; then
    run_install
    touch "$SENTINEL"
  fi
fi

# === D-14: retry loop (3 attempts, exponential backoff 1s / 2s / 4s) ===
EXEC_CMD='npm run dev -- --hostname 0.0.0.0 --port 3000'
ATTEMPT=1
DELAY=1
while (( ATTEMPT <= 3 )); do
  echo "[pivota] attempt $ATTEMPT: $EXEC_CMD"
  if bash -c "$EXEC_CMD"; then
    echo "[pivota] inner command exited 0; propagating success"
    exit 0
  fi
  EXIT_CODE=$?
  if (( ATTEMPT == 3 )); then
    echo "[pivota] all 3 attempts failed (last exit=$EXIT_CODE); surfacing failure"
    exit "$EXIT_CODE"
  fi
  echo "[pivota] attempt $ATTEMPT failed (exit=$EXIT_CODE); retrying in ${DELAY}s"
  sleep "$DELAY"
  DELAY=$(( DELAY * 2 ))
  ATTEMPT=$(( ATTEMPT + 1 ))
done

# Unreachable, but keep for analyzer happiness
exit 1
# === END PIVOTA PREAMBLE ===
# Below this marker, projects may add custom shutdown / setup logic.
# This region is PRESERVED across regenerations (plan 06's regen logic detects
# the marker and re-appends user content verbatim after re-emitting the preamble).
